blog_url: https://rpc.cnblogs.com/metaweblog/htp168
blog_id: htp168
username: htp168
password: htp168A163Dcom

# 是否生成图片替换后本地文件,默认False关闭
gen_network_file: False

# 上传后是否发布，默认未发布，设置True为发布
publish: True

# 图片自定义显示格式，默认不设置
# img_format: "<center><img src="{}" style="width:100%;" /></center>" 设置居中和宽度
# img_format: typora 还原typora图片样式，居中，设置zoom，上传后无需再手动调整图片大小
img_format: ""